SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ghost_BM_LoginSequence](
	[Ls_Id] [BIGINT] NOT NULL,
	[Ls_LoginTokenId] [NVARCHAR](50) NOT NULL,
	[Ls_LoginTime] [DATETIME] NOT NULL,
	[Ls_IP] [NVARCHAR](50) NULL,
	[Ls_ServerVariables] [NVARCHAR](MAX) NULL,
	[Ls_RecordTime] [DATETIME] NOT NULL,
	[Ls_UpdateTime] [DATETIME] NULL,
PRIMARY KEY CLUSTERED 
(
	[Ls_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


